[package]
name = "fib-host"
version = "0.1.0"
edition = "2024"

[dependencies]
wasmtime = "33.0.0"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
futures-util = "0.3.31"
core_affinity = "0.8.3"